/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bees_and_honey_combs.glb --types 
*/

import * as THREE from 'three'
import React, { type JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { type GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Honey_Drip_Honey_Liquid_Material_0: THREE.Mesh
    Honey_Drip1_Honey_Liquid_Material_0: THREE.Mesh
    Object_18: THREE.SkinnedMesh
    Object_34: THREE.SkinnedMesh
    Object_50: THREE.SkinnedMesh
    Z_Plane1_Z_Lambert_0: THREE.Mesh
    Comb_Honey_Comb_Material_0: THREE.Mesh
    ['0']: THREE.Mesh
    ['1']: THREE.Mesh
    ['2']: THREE.Mesh
    ['3']: THREE.Mesh
    HoneyBackground_Honey_Background_Material_0: THREE.Mesh
    J_Bee_Body_02: THREE.Bone
    J_Bee_Body_013: THREE.Bone
    J_Bee_Body_025: THREE.Bone
  }
  materials: {
    Honey_Liquid_Material: THREE.MeshBasicMaterial
    Bee_Material_001: THREE.MeshBasicMaterial
    Bee_Material_002: THREE.MeshBasicMaterial
    Z_Lambert: THREE.MeshBasicMaterial
    Honey_Comb_Material: THREE.MeshBasicMaterial
    Honey_Background_Material: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function HeroModel(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group | null>(null)
  const { scene, animations } = useGLTF('/bees_and_honey_combs.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
  const action = actions?.["Take 001"]

  if (action) {
    action.reset().fadeIn(0.5).play()
  }

  return () => {
    action?.fadeOut(0.5)
    // não retornar a action!
  }
}, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="2cb76bbe27f041b581a7c260e43f268cfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="BeeHiveGroup">
                  <group name="Honey_Drip" position={[0.463, -0.95, 0.759]} scale={0}>
                    <mesh name="Honey_Drip_Honey_Liquid_Material_0" geometry={nodes.Honey_Drip_Honey_Liquid_Material_0.geometry} material={materials.Honey_Liquid_Material} position={[-512, 0, 0]} />
                  </group>
                  <group name="Honey_Drip1" position={[-1.388, 0.842, 0.751]} scale={[0.806, 1, 1]}>
                    <mesh name="Honey_Drip1_Honey_Liquid_Material_0" geometry={nodes.Honey_Drip1_Honey_Liquid_Material_0.geometry} material={materials.Honey_Liquid_Material} />
                  </group>
                  <group name="Bee_Mesh">
                    <group name="Object_17">
                      <group name="J_Bee_Main_01" position={[-0.026, -0.897, -3.03]} rotation={[0, 0, 0]}>
                        <primitive object={nodes.J_Bee_Body_02} />
                        <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Bee_Material_001} skeleton={nodes.Object_18.skeleton} />
                      </group>
                      <group name="Bee_Model" />
                    </group>
                  </group>
                  <group name="Bee_Mesh1">
                    <group name="Object_33">
                      <group name="J_Bee_Main_012" position={[2.209, 1.165, -2.537]} rotation={[0, 1.366, 1.032]}>
                        <primitive object={nodes.J_Bee_Body_013} />
                        <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Bee_Material_001} skeleton={nodes.Object_34.skeleton} />
                      </group>
                      <group name="Bee_Model001" />
                    </group>
                  </group>
                  <group name="Bee_Mesh_Sleeping_">
                    <group name="Object_49">
                      <group name="Bee_Model002" />
                      <group name="J_Bee_Main_024" position={[0.855, 1.384, -0.259]} rotation={[-1.713, -1.405, -1.797]}>
                        <primitive object={nodes.J_Bee_Body_025} />
                        <skinnedMesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.Bee_Material_001} skeleton={nodes.Object_50.skeleton} />
                      </group>
                    </group>
                  </group>
                  <group name="Bee_One_Path" />
                  <group name="Bee_Two_Path" />
                  <group name="BeeHiveMesh">
                    <group name="HoneyComb" />
                    <group name="ZLayer">
                      <group name="Z_Plane1" position={[0.519, 1.39, 0.562]} rotation={[0, 0.117, 0]} scale={0}>
                        <mesh name="Z_Plane1_Z_Lambert_0" geometry={nodes.Z_Plane1_Z_Lambert_0.geometry} material={materials.Z_Lambert} position={[-24576, -131072, -28672]} scale={0.999} />
                      </group>
                    </group>
                  </group>
                  <group name="DNT">
                    <group name="Honey_Left_Group" />
                    <group name="Honey_Low_Group" />
                    <group name="Honey_Middle_Group" />
                    <group name="Honey_Right_Group" />
                  </group>
                  <group name="group">
                    <group name="Comb">
                      <mesh name="Comb_Honey_Comb_Material_0" geometry={nodes.Comb_Honey_Comb_Material_0.geometry} material={materials.Honey_Comb_Material} />
                    </group>
                  </group>
                  <group name="Honey_Left" position={[0.848, 1.131, 0.07]}>
                    <mesh name="0" geometry={nodes['0'].geometry} material={materials.Honey_Liquid_Material} morphTargetDictionary={nodes['0'].morphTargetDictionary} morphTargetInfluences={nodes['0'].morphTargetInfluences} />
                  </group>
                  <group name="Honey_Low" position={[-0.825, -1.957, 0.237]}>
                    <mesh name="1" geometry={nodes['1'].geometry} material={materials.Honey_Liquid_Material} morphTargetDictionary={nodes['1'].morphTargetDictionary} morphTargetInfluences={nodes['1'].morphTargetInfluences} />
                  </group>
                  <group name="Honey_Middle" position={[0.041, -0.377, -0.019]}>
                    <mesh name="2" geometry={nodes['2'].geometry} material={materials.Honey_Liquid_Material} morphTargetDictionary={nodes['2'].morphTargetDictionary} morphTargetInfluences={nodes['2'].morphTargetInfluences} />
                  </group>
                  <group name="Honey_Right" position={[-0.879, 1.108, 0]}>
                    <mesh name="3" geometry={nodes['3'].geometry} material={materials.Honey_Liquid_Material} morphTargetDictionary={nodes['3'].morphTargetDictionary} morphTargetInfluences={nodes['3'].morphTargetInfluences} />
                  </group>
                  {/* <group name="HoneyBackground">
                    <mesh name="HoneyBackground_Honey_Background_Material_0" geometry={nodes.HoneyBackground_Honey_Background_Material_0.geometry} material={materials.Honey_Background_Material} />
                  </group> */}
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bees_and_honey_combs.glb')
